//
//  Constants.h
//  WhackABoss
//
//  Created by Jonathan Enzinna on 2/6/10.
//  Copyright Vault Head Games 2010. All rights reserved.
//

#define OPENFEINT_PRODUCTKEY @"LfsKTVWw0sk9vi6ECoNjw"
#define OPENFEINT_SECRETKEY @"yjW20MFgmDOsZE4SQIggP75ftCD9axqAMok3jXjBU"

#define VERSION_MAJOR	0
#define VERSION_MINOR	0
#define VERSION_REV		1
#define VERSION_TAG		@"A"

#define TARGET_FPS 29.97

/*
 BASE_DELAY = DIFF_MOD log <TARGET LAST LEVEL>
 LAST_LEVEL = (BASE_DELAY / BASE_DIFF) ^ 10
 */
#define BASELINE_DIFFICULTY_MODIFIER 2
#define BASELINE_POPUP_DELAY 4
#define MAXIMUM_CREATURE_LEVEL_MODIFIER 0.1
#define TICK_NEW_CREATURE_PROBABILITY_MODIFIER 0.25
#define NEW_LEVEL_SCORE_REQUIREMENT 2500

typedef enum
{
	WIN,
	FAIL,
	CARL_GOES_POSTAL,
	SEXUAL_HARASSMENT
} EndGameCondition;